version: '3.7'
services:
  app1:
    image: ryanpurchase288/app1:latest
    build: ./app1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    deploy:
      replicas: 3
  app2:
    image: ryanpurchase288/app2:latest
    build: ./app2
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
    deploy:
      replicas: 3
